           version: '2'

           services:
             app:
               image: 'customer-0.0.1:latest'
               build:
                 context: .
               container_name: app
               depends_on:
                 - db
               environment:
                 - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customer
                 - SPRING_DATASOURCE_USERNAME=ccor
                 - SPRING_DATASOURCE_PASSWORD=1027
                 - SPRING_JPA_HIBERNATE_DDL_AUTO=update
                 - SPRING_JPA_SHOW_SQL=true
               ports:
                 - 8080:8080

             db:
               image: 'postgres:13.1-alpine'
               container_name: db
               environment:
                 - POSTGRES_USER=ccor
                 - POSTGRES_PASSWORD=1027